# INTRODUCTION TO NUMPY FUNCTIONS [MATHEMATICS]

![Mathematics Programming](https://www.kindpng.com/picc/m/273-2736876_maths-logo-hd-png-download.png)

In [1]:
#addition and subtraction
5+5

10

In [6]:
my_list = [i for i in range(1000000)]
list_size = len(my_list)
print(my_list[:10])
import numpy as np
arr = np.array(my_list)
print("array size", len(arr))
print(arr[:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array size 1000000
[0 1 2 3 4 5 6 7 8 9]


In [11]:
import numpy as np
list = [1,2,3,4,5]
a = np.array(list)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [2]:
import numpy as np

In [21]:
b = (np.arange(1,6))
print(b)

[1 2 3 4 5]


In [22]:
print(a+b)

[ 2  4  6  8 10]


In [23]:
lst = [1,2,3,4,5]
list = [1,2,3,4,5]
print(lst+list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [33]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [37]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
print(np.full((2,2),8))

[[8 8]
 [8 8]]


In [146]:
print(np.empty((2,2)))

[[0. 0.]
 [0. 0.]]


In [47]:
a = np.array ([[1,2,3],
                  [5,6,7]])
print (a)

[[1 2 3]
 [5 6 7]]


In [10]:
a = np.array([[3,3,2,1,6],[54,56,32,87,9]])
a

array([[ 3,  3,  2,  1,  6],
       [54, 56, 32, 87,  9]])

In [16]:
a[0,-2]

1

In [18]:
a[0, :]

array([3, 3, 2, 1, 6])

In [19]:
a[1,3] = 67
a

array([[ 3,  3,  2,  1,  6],
       [54, 56, 32, 67,  9]])

In [20]:
a

array([[ 3,  3,  2,  1,  6],
       [54, 56, 32, 67,  9]])

In [21]:
a[1,3]

67

In [22]:
a[:,4]=0
a

array([[ 3,  3,  2,  1,  0],
       [54, 56, 32, 67,  0]])

In [30]:
b = np.array([[[3,4,2,6],[4,5,2,7]],[[6,7,3,4],[5,6,4,3]]])
b

array([[[3, 4, 2, 6],
        [4, 5, 2, 7]],

       [[6, 7, 3, 4],
        [5, 6, 4, 3]]])

In [31]:
b[0,1,3]

7

# Initializing different types of arrays


In [48]:
c=np.zeros((2,2,4,5))
c

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [62]:
d=np.ones((2,4,3), dtype = 'int32')
d

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [95]:
 e = np.full((10,10),100)
e

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

# RANDOM INTEGER VALUES

In [94]:
x= np.random.randint(-200,200,size=(20,10))
x

array([[ 136,  -98,  -46,   17, -128, -127,  128,  -53,  102,   -2],
       [  29,  -76, -197,  -47,  -51,   74,  199,  108,   69,  -68],
       [  76, -138, -137,   64, -146,   15,   90,  126,  144, -175],
       [ -51,   27, -174,  -96,  127,  142,  -17,  149,   26,  155],
       [  70,  -77,  -28, -189, -178,    0,   30,  126,   63,  -91],
       [  68,  152, -119,  114,   45,   41,  -11,   96, -182,  -94],
       [ -96,   -7,  134,  -61,  168, -137,  -22,  147,   75,   37],
       [ 161,  -21,  175,   30, -119,   39, -196,   11,   85, -160],
       [ -64,    4,   54,  -40,  102,   12,   88,  117,  -19, -110],
       [  25,   65,  112,  -72,   86,  154,   96,   -5,  -39,  168],
       [  91,  136,  -50,  179,  -91, -114, -171, -192,  180, -139],
       [  16,   21, -114,  -87,  -32,   63,   -2,   70, -142,  -63],
       [-157,   14,   69,   48,   79,  -69,   13, -101,   14,  118],
       [  -4,  116,  144,  -30, -103,  172,   26,  148,   35,  108],
       [ -47,  155,   13,  138,   

# IDENTITY MATRIX

In [97]:
i=np.identity(6)
i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# MATRIX MODELS

In [144]:
fx = np.full((11,11),99)
fx
z = np.zeros((3,3))
z[1,1] =0
fx[3:6,3:6]=z
fx

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99,  0,  0,  0, 99, 99, 99, 99, 99],
       [99, 99, 99,  0,  0,  0, 99, 99, 99, 99, 99],
       [99, 99, 99,  0,  0,  0, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]])

# NB WHEN REPLACING FUNCTIONS

In [152]:
r = np.array([1,2,3,4,5])
c=r.copy()
c[0]=1000
c


array([1000,    2,    3,    4,    5])

# MATHEMATICS

In [165]:
aa=np.array([[10,20,30,],[40,50,60]])
aa

array([[10, 20, 30],
       [40, 50, 60]])

In [173]:
aa+2


array([[12, 22, 32],
       [42, 52, 62]])

In [174]:
aa**2

array([[ 100,  400,  900],
       [1600, 2500, 3600]], dtype=int32)

In [175]:
ab=np.array([[1,3,7],[2,4,9]])
ab

array([[1, 3, 7],
       [2, 4, 9]])

In [176]:
aa+ab

array([[11, 23, 37],
       [42, 54, 69]])

In [178]:
np.sin(aa)

array([[-0.54402111,  0.91294525, -0.98803162],
       [ 0.74511316, -0.26237485, -0.30481062]])

In [185]:
np.gcd(20,30)

10

In [188]:
np.cbrt(27)

3.0

### FOR MORE MATH FUNCTIONS VISIT: https://numpy.org/doc/stable/reference/routines.math.html 


# LINEAR ALGEBRA


In [206]:
ad = np.full((5,4),16)
ae = np.full((4,3),8)
np.matmul(ad,ae)


array([[512, 512, 512],
       [512, 512, 512],
       [512, 512, 512],
       [512, 512, 512],
       [512, 512, 512]])

In [212]:
b = np.array([[[3,4,2,6],[4,5,2,7],[6,7,3,4],[5,6,4,3]]])
b

array([[[3, 4, 2, 6],
        [4, 5, 2, 7],
        [6, 7, 3, 4],
        [5, 6, 4, 3]]])

In [207]:
# matrix multiplications
ah = np.matmul(ad,b)

array([[[288, 352, 176, 320],
        [288, 352, 176, 320],
        [288, 352, 176, 320],
        [288, 352, 176, 320],
        [288, 352, 176, 320]]])

In [215]:
# finding determinants
b = np.array([[[3,4,2,6],[4,5,2,7],[6,7,3,4],[5,6,4,3]]])
np.linalg.det(b)

array([-5.])

In [218]:
# finding eigenvalues
np.linalg.eigvals(b)

array([[17.56805391+0.j        , -0.06381114+0.j        ,
        -1.75212138+1.17907773j, -1.75212138-1.17907773j]])

### for more algebra functions: https://numpy.org/doc/stable/reference/routines.linalg.html


#  STATISTICS




In [219]:
b = np.array([[[3,4,2,6],[4,5,2,7],[6,7,3,4],[5,6,4,3]]])
b

array([[[3, 4, 2, 6],
        [4, 5, 2, 7],
        [6, 7, 3, 4],
        [5, 6, 4, 3]]])

In [220]:
np.min(b)

2

In [223]:
np.max(b)

7

In [224]:
np.min(b,axis =2)

array([[2, 2, 3, 3]])

In [225]:
np.sum(b)

71

In [226]:
b.shape

(1, 4, 4)

# importing data from a file

import os
os.getcwd()

In [234]:
os.chdir('C:\\Users\\Isaac\\Desktop')

In [252]:
v = np.genfromtxt('data.txt',delimiter = ',')
q = v.astype('int32')
q

array([  43,   34,    5,    3,  434,    5,    5,    5,  454,   66, 8635,
         44,    5,    6,    5,    7,    8,  898,   76,    5,    5,    4,
          4,    4,    5,   56,    7,    8,   78,    9,    8,   68,   68,
         68,    8,    8,   68,   68,   68,    7,   56,   56,    7,  878,
         79, 2435,    4,   56,    7,   68,  788,  224,    5,   46,    7,
         64,   46,   56,   96,   45,   35,   26,    5,   76,   86])

#### boolean analysis

In [263]:
q[q>50]

array([ 434,  454,   66, 8635,  898,   76,   56,   78,   68,   68,   68,
         68,   68,   68,   56,   56,  878,   79, 2435,   56,   68,  788,
        224,   64,   56,   96,   76,   86])

In [264]:
q>50

array([False, False, False, False,  True, False, False, False,  True,
        True,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False,  True, False,
       False,  True, False, False,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True,  True])

In [273]:
np.any(q > 1000, axis =0)

True